In [1]:
import numpy as np

In [2]:
a = np.array([12,23,34,15,64,12])

In [3]:
print(a)

[12 23 34 15 64 12]


In [4]:
a

array([12, 23, 34, 15, 64, 12])

In [8]:
a.dtype

dtype('int64')

In [9]:
b = np.array([12,23,34,15,64,12, 'Adi', 43.44])

In [10]:
b

array(['12', '23', '34', '15', '64', '12', 'Adi', '43.44'], dtype='<U32')

In [13]:
a = np.array([12,23,34,15,64,12, 11.12])
a

array([12.  , 23.  , 34.  , 15.  , 64.  , 12.  , 11.12])

In [14]:
x = np.arange(10)

In [15]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x = np.arange(3,10)

In [17]:
x

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
x = np.arange(-5,5,0.25)

In [21]:
x

array([-5.  , -4.75, -4.5 , -4.25, -4.  , -3.75, -3.5 , -3.25, -3.  ,
       -2.75, -2.5 , -2.25, -2.  , -1.75, -1.5 , -1.25, -1.  , -0.75,
       -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,
        1.75,  2.  ,  2.25,  2.5 ,  2.75,  3.  ,  3.25,  3.5 ,  3.75,
        4.  ,  4.25,  4.5 ,  4.75])

In [22]:
x.ndim

1

In [23]:
arr =np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [24]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
arr.ndim

2

In [26]:
a = np.array([12,23,34,15,64,12])

In [27]:
a

array([12, 23, 34, 15, 64, 12])

In [32]:
a[1:]

array([23, 34, 15, 64, 12])

In [33]:
a[:4]

array([12, 23, 34, 15])

In [29]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
# slicing

In [34]:
arr[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [35]:
arr[1:4, 1:]

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [37]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [36]:
arr[[0,2,3], :]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [38]:
arr[1,1]

5

In [39]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
arr.shape

(4, 3)

In [41]:
arr.size

12

In [42]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [44]:
arr.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [43]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [45]:
arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [46]:
arr.reshape(2,3,2).ndim

3

### Pandas Series

In [48]:
import pandas as pd

In [49]:
s = pd.Series([23,23,45,32,12])
s

0    23
1    23
2    45
3    32
4    12
dtype: int64

In [50]:
s[2]

45

In [52]:
s = pd.Series([23,23,45,32,12], index = range(101,106))
s

101    23
102    23
103    45
104    32
105    12
dtype: int64

### Pandas Dataframe

In [54]:
a = [67, 71, 57, 82, 79]
b = ['Raj', 'Natasha', 'Riya', 'Ravi', 'Anand']
c = [21, 22, 21, 23, 22]

In [59]:
df = pd.DataFrame({
    'name': b,
    'marks': a,
    'age': c
})

In [60]:
df

name  marks  age
0      Raj     67   21
1  Natasha     71   22
2     Riya     57   21
3     Ravi     82   23
4    Anand     79   22

In [61]:
df.shape

(5, 3)

In [63]:
df.dtypes

name     object
marks     int64
age       int64
dtype: object